declare const Buffer: {
  from(value: ArrayBuffer | ArrayLike<number> | string, encoding?: string): {
    toString(encoding?: string): string;
  };
};

declare const qrcode: any;

type AnyFunction = (...args: any[]) => any;

interface AmbientLightSensor extends EventTarget {
  illuminance: number;
  start(): void;
  stop(): void;
}

interface AmbientLightSensorConstructor {
  new(options?: { frequency?: number }): AmbientLightSensor;
}

interface Window {
  _demoLoadingProfileId?: string;
  _snpTableCache?: unknown;
  APP_VERSION?: string;
  applyAccentOverride?: () => void;
  callClaudeAPI?: (request: {
    system?: string;
    messages: Array<{ role: string; content: string }>;
    maxTokens?: number;
  }) => Promise<{ text?: string }> | { text?: string };
  cashuCheckFundingStatus?: AnyFunction;
  cashuCheckProofStates?: AnyFunction;
  cashuClearPendingDeposit?: AnyFunction;
  cashuClearPendingWithdraw?: AnyFunction;
  cashuCreateFundingInvoice?: AnyFunction;
  cashuCreateWithdrawQuote?: AnyFunction;
  cashuDepositToNode?: AnyFunction;
  cashuDestroyWalletDB?: () => Promise<void> | void;
  cashuExecuteWithdraw?: AnyFunction;
  cashuExportWallet?: AnyFunction;
  cashuGenerateWalletSeed?: AnyFunction;
  cashuGetBalance?: AnyFunction;
  cashuGetFeePct?: AnyFunction;
  cashuGetMaxWithdrawable?: AnyFunction;
  cashuGetMintUrl?: () => Promise<string | null> | string | null;
  cashuGetWalletMnemonic?: AnyFunction;
  cashuHasWalletSeed?: AnyFunction;
  cashuImportWallet?: AnyFunction;
  cashuReceiveToken?: AnyFunction;
  cashuRecoverPendingDeposit?: AnyFunction;
  cashuRecoverPendingWithdraw?: AnyFunction;
  cashuRestoreWalletFromSeed?: AnyFunction;
  cashuSendAsToken?: AnyFunction;
  cashuSetMintUrl?: (url: string) => Promise<void> | void;
  cashuWithdrawToAddress?: AnyFunction;
  Chart?: new (canvas: HTMLCanvasElement, config: unknown) => { destroy(): void };
  closeModal: () => void;
  closeEMFInterpretation: AnyFunction;
  closeChangelog: () => void;
  closeChatPanel: () => void;
  closeFeedbackModal: () => void;
  closeImportModal: () => void;
  closeReportBuilder?: () => void;
  closeRestoreMnemonicDialog?: () => void;
  closeSettings?: () => void;
  closeSettingsModal: () => void;
  closeSummaryModal?: () => void;
  closeSyncSetup?: () => Promise<void> | void;
  closeTweaksPanel: () => void;
  clearE2EESession?: AnyFunction;
  cleanupDiscussionState?: AnyFunction;
  destroyAllCharts?: () => void;
  detectDNAFile?: (header: string) => string | null;
  ensureActiveThread?: () => void;
  exportAllDataJSON?: () => Promise<void> | void;
  exportClientJSON?: (profileId: string, includeChat?: boolean) => Promise<void> | void;
  getInitialView?: () => string;
  getActiveData?: AnyFunction;
  getActivePersonality?: AnyFunction;
  getActiveProfileId?: () => string | null;
  getProfileHeight?: (profileId: string) => { height?: number | string | null; unit?: string | null };
  getProfileLocation?: AnyFunction;
  getOllamaConfig?: AnyFunction;
  getProfiles?: () => Array<{ id?: string; name?: string | null; sex?: string | null }>;
  HAPLOGROUP_LIST?: string[];
  hasAIProvider?: () => boolean;
  fetchAtmosphere?: AnyFunction;
  filterThreadList?: AnyFunction;
  reconstructSpectrum?: AnyFunction;
  computeChannelDoses?: AnyFunction;
  CHANNEL_DISPLAY?: Record<string, { icon?: string; label?: string; what?: string; dailyTarget?: number }>;
  dailyChannelBreakdown?: AnyFunction;
  dailyVitaminDIUBreakdown?: AnyFunction;
  channelTier?: (value: any, channelKey?: string) => number;
  formatChannelUnit?: AnyFunction;
  BODY_REGIONS?: any[];
  renderBodySilhouette?: (selected?: Set<string>) => string;
  bindBodySilhouette?: (rootEl: Element, selected: Set<string>, onChange?: (selected: Set<string>) => void) => void;
  synthesizeDeviceSpectrum?: AnyFunction;
  effectiveDeviceForMode?: AnyFunction;
  validateModeCoupling?: AnyFunction;
  erythemalSED?: AnyFunction;
  fractionOfMED?: AnyFunction;
  retinalUVdose?: AnyFunction;
  vitaminDIU?: AnyFunction;
  vitaminDIUPerSession?: AnyFunction;
  VITD_DAILY_SATURATION_IU?: number;
  pbmJoulesPerCm2?: AnyFunction;
  circadianMelanopicLux?: AnyFunction;
  geneticVitaminDMultiplier?: AnyFunction;
  renderLightChannelsLive?: AnyFunction;
  renderLightTodayStrip?: AnyFunction;
  renderSunSessionRow?: AnyFunction;
  rollingChannelTotals?: (days?: number) => Record<string, number>;
  rollingVitaminDIU?: (days?: number) => number;
  weeklyChannelTier?: (value: number, channel?: string) => number;
  tierLabel?: (tier: number) => string;
  getSessions?: () => any[];
  getActiveSession?: AnyFunction;
  cumulativeMEDToday?: AnyFunction;
  cumulativeMEDYesterday?: AnyFunction;
  vitaminDBudgetStatus?: AnyFunction;
  maybeAnalyzeDeviceSessionAfterFinish?: AnyFunction;
  _labState?: { currentProfile?: string | null };
  handleDNAFile: (file: File) => Promise<void> | void;
  handleChatKeydown?: AnyFunction;
  handleMtDNAFile?: (file: File) => Promise<void> | void;
  importDataJSON: (file: File) => Promise<void> | void;
  deleteImportSnapshot?: (snapshotId: string) => Promise<boolean> | boolean;
  isDebugMode?: () => boolean;
  isImportRunning?: () => boolean;
  initChatImageHandlers: () => void;
  loadFocusCard?: AnyFunction;
  _pendingImport?: any;
  _pendingImportRefLookup?: Record<string, any> | null;
  _batchImportResolve?: ((action: string) => void) | null;
  _batchImportContext?: { current: number; total: number } | null;
  _lastOllamaModelDetails?: any[];
  _lastIsOllamaServer?: boolean;
  _settingsHadProvider?: boolean;
  _veniceAttestation?: any;
  _ppqAttestation?: any;
  _rsCashuBackupTimer?: ReturnType<typeof setTimeout>;
  _walletSeedThenAction?: AnyFunction | null;
  _getActiveProfileId?: () => string | null;
  _openChatAfterInit?: boolean;
  _openSettingsAfterInit?: string;
  loadDemoData?: (sex?: string) => Promise<void> | void;
  loadChatHistory?: () => Promise<void> | void;
  loadChatPersonality?: () => void;
  loadChatThreads?: () => void;
  JSZip?: {
    loadAsync(input: ArrayBuffer | Blob): Promise<{
      files: Record<string, {
        dir: boolean;
        name: string;
        async(type: 'blob'): Promise<Blob>;
      }>;
    }>;
  };
  mammoth?: {
    extractRawText(input: { arrayBuffer: ArrayBuffer }): Promise<{ value?: string }>;
  };
  navigate: (route: string, options?: any) => void;
  nostrGetSelectedNode?: () => string | null;
  nostrDiscoverNodes?: AnyFunction;
  nostrSetSelectedNode?: (url: string) => void;
  openChatPanel: AnyFunction;
  openEMFAssessmentEditor?: () => void;
  openSettingsModal: (tab?: string) => void;
  openChatProviderQuiz?: AnyFunction;
  openImportReviewFromSnapshot?: (snapshotId: string) => void;
  pdfjsLib?: unknown;
  openProfileShareModal?: (profileId?: string) => void;
  quickLogSunSession?: () => Promise<void> | void;
  openDetailedSessionDialog?: AnyFunction;
  requestPreciseLocation?: AnyFunction;
  pauseSunSession?: (id?: string) => Promise<void> | void;
  resumeSunSession?: (id?: string) => Promise<void> | void;
  flipSidesMidSession?: (id?: string) => Promise<void> | void;
  changeCoverageMidSession?: (id?: string) => Promise<void> | void;
  applySunscreenMidSession?: (id?: string) => Promise<void> | void;
  setOzoneOverrideMidSession?: () => Promise<void> | void;
  _forgotStopPrompt?: (id?: string) => Promise<void> | void;
  _openChannelOnLightPage?: (channel?: string) => void;
  _applyAtmOverrides?: AnyFunction;
  _refreshSunSurfaces?: AnyFunction;
  _resumeActiveTickerIfNeeded?: AnyFunction;
  refreshChartThemeColors?: (options?: { batchSize?: number }) => void;
  refreshMobileDashboardActiveTab?: AnyFunction;
  refreshSettingsWearables?: () => void;
  rememberModalTrigger?: () => void;
  renderChatMessages?: AnyFunction;
  renderMenstrualCycleSection?: AnyFunction;
  renderSavedSummaries?: AnyFunction;
  renderSupplementsSection?: AnyFunction;
  renderThreadList?: () => void;
  restoreDiscussionContinuePrompt?: AnyFunction;
  scheduleChartThemeRefresh?: () => void;
  saveChatHistory?: AnyFunction;
  setManualHaplogroup?: (haplogroup: string) => Promise<void> | void;
  setChatWebSearchEnabled?: AnyFunction;
  setOnboardingFocus?: AnyFunction;
  setProfileHeight?: AnyFunction;
  showConfirmDialog?: (message: string) => Promise<boolean> | boolean;
  showPromptDialog?: (message: string, options?: any) => Promise<string | null> | string | null;
  showNotification?: (message: string, type?: string, timeoutMs?: number) => void;
  showInsufficientBalanceDialog?: () => void;
  isChatStreaming?: () => boolean;
  openMenstrualCycleEditor?: AnyFunction;
  openSupplementsEditor?: AnyFunction;
  _resumeAI?: AnyFunction;
  recordChange?: AnyFunction;
  sendChatMessage?: AnyFunction;
  switchAIProvider?: AnyFunction;
  toggleChatPanel: () => void;
  togglePersonalityBar?: AnyFunction;
  updateChatHeaderModel?: AnyFunction;
  updateAttachButtonVisibility: () => void;
  updateChatNudge: () => void;
  updatePrivacyStatusCard?: AnyFunction;
  refreshWebSearchToggle?: AnyFunction;
  saveImportedData?: AnyFunction;
  _getRelevantSNPs?: AnyFunction;
  deleteNote?: AnyFunction;
  detectWearableTrendSlots?: AnyFunction;
  loadContextCardTips?: AnyFunction;
  openNoteEditor?: AnyFunction;
  showDetailModal?: AnyFunction;
  triggerDNAFilePicker?: AnyFunction;
  renderLightTools?: AnyFunction;
  renderSunDataSourceSettings?: AnyFunction;
  computeUVConfidence?: AnyFunction;
  getMeteoConfig?: AnyFunction;
  ingredientDailyTotal?: AnyFunction;
  maybeShowAnalyticsConsent?: () => void;
  purgeMeteoCache?: AnyFunction;
  rehydrateStaleSessions?: () => Promise<{ rehydrated?: number }>;
  SUN_ENGINE_VERSION?: number;
  AmbientLightSensor?: AmbientLightSensorConstructor;
  addRoom?: AnyFunction;
  getSunCoords?: AnyFunction;
  hydrateSession?: AnyFunction;
  logCompletedSession?: AnyFunction;
  getMeasurementsForRoom?: AnyFunction;
  renderBurdenInterp?: AnyFunction;
  saveMeasurement?: AnyFunction;
  openChatPanel: AnyFunction;
  openCCTMeter?: AnyFunction;
  openDarknessMeter?: AnyFunction;
  openFlickerDetector?: AnyFunction;
  openLuxMeter?: AnyFunction;
  openSpectrumClassifier?: AnyFunction;
  _fitbitAuth?: unknown;
  _appleHealth?: unknown;
  _ouraAuth?: unknown;
  _polarAuth?: unknown;
  _ultrahumanAuth?: unknown;
  _whoopAuth?: unknown;
  _withingsAuth?: unknown;
  updateChatHeaderTitle?: () => void;
  updateDiscussButton?: () => void;
  updateHeaderDates?: () => void;
  updateHeaderRangeToggle?: () => void;
  updatePersonalityBar?: () => void;
  updateSettingsUI?: () => void;
  updateTweaksUI?: () => void;
}

declare var getMeasurementsForRoom: AnyFunction | undefined;
declare var navigate: AnyFunction | undefined;
declare var openCCTMeter: AnyFunction | undefined;
declare var openDarknessMeter: AnyFunction | undefined;
declare var openFlickerDetector: AnyFunction | undefined;
declare var openLuxMeter: AnyFunction | undefined;
declare var openSpectrumClassifier: AnyFunction | undefined;
declare var renderBurdenInterp: AnyFunction | undefined;
declare var ingredientDailyTotal: AnyFunction | undefined;
