declare const Buffer: {
  from(value: ArrayBuffer | ArrayLike<number> | string, encoding?: string): {
    toString(encoding?: string): string;
  };
};

type AnyFunction = (...args: any[]) => any;

interface AmbientLightSensor extends EventTarget {
  illuminance: number;
  start(): void;
  stop(): void;
}

interface AmbientLightSensorConstructor {
  new(options?: { frequency?: number }): AmbientLightSensor;
}

interface Window {
  _demoLoadingProfileId?: string;
  _snpTableCache?: unknown;
  APP_VERSION?: string;
  applyAccentOverride?: () => void;
  buildSidebar?: AnyFunction;
  callClaudeAPI?: (request: {
    system?: string;
    messages: Array<{ role: string; content: string }>;
    maxTokens?: number;
  }) => Promise<{ text?: string }> | { text?: string };
  cashuDestroyWalletDB?: () => Promise<void> | void;
  cashuGetMintUrl?: () => Promise<string | null> | string | null;
  cashuRestoreWalletFromSeed?: (seed: string) => Promise<void> | void;
  cashuSetMintUrl?: (url: string) => Promise<void> | void;
  Chart?: new (canvas: HTMLCanvasElement, config: unknown) => { destroy(): void };
  closeModal?: () => void;
  closeSettings?: () => void;
  destroyAllCharts?: () => void;
  detectDNAFile?: (header: string) => string | null;
  ensureActiveThread?: () => void;
  exportAllDataJSON?: () => Promise<void> | void;
  exportClientJSON?: (profileId: string, includeChat?: boolean) => Promise<void> | void;
  getInitialView?: () => string;
  getActiveProfileId?: () => string | null;
  getProfileHeight?: (profileId: string) => { height?: number | string | null; unit?: string | null };
  getProfileLocation?: AnyFunction;
  getProfiles?: () => Array<{ id?: string; name?: string | null; sex?: string | null }>;
  HAPLOGROUP_LIST?: string[];
  hasAIProvider?: () => boolean;
  fetchAtmosphere?: AnyFunction;
  reconstructSpectrum?: AnyFunction;
  computeChannelDoses?: AnyFunction;
  CHANNEL_DISPLAY?: Record<string, { icon?: string; label?: string; what?: string; dailyTarget?: number }>;
  dailyChannelBreakdown?: AnyFunction;
  dailyVitaminDIUBreakdown?: AnyFunction;
  channelTier?: (value: any, channelKey?: string) => number;
  formatChannelUnit?: AnyFunction;
  BODY_REGIONS?: any[];
  renderBodySilhouette?: (selected?: Set<string>) => string;
  bindBodySilhouette?: (rootEl: Element, selected: Set<string>, onChange?: (selected: Set<string>) => void) => void;
  synthesizeDeviceSpectrum?: AnyFunction;
  effectiveDeviceForMode?: AnyFunction;
  validateModeCoupling?: AnyFunction;
  erythemalSED?: AnyFunction;
  fractionOfMED?: AnyFunction;
  retinalUVdose?: AnyFunction;
  solarZenithAngle?: AnyFunction;
  interpolateAtmosphere?: AnyFunction;
  vitaminDIU?: AnyFunction;
  vitaminDIUPerSession?: AnyFunction;
  VITD_DAILY_SATURATION_IU?: number;
  pbmJoulesPerCm2?: AnyFunction;
  circadianMelanopicLux?: AnyFunction;
  _skinTypeToFitzpatrick?: AnyFunction;
  geneticVitaminDMultiplier?: AnyFunction;
  renderSessionAIInline?: AnyFunction;
  renderSessionAIDetail?: AnyFunction;
  renderDeviceSessionAIDetail?: AnyFunction;
  renderDeviceSessionAIInline?: AnyFunction;
  renderLightChannelsLive?: AnyFunction;
  renderLightTodayDashboardChip?: AnyFunction;
  renderLightTodayHero?: AnyFunction;
  renderLightTodayStrip?: AnyFunction;
  renderSunSessionRow?: AnyFunction;
  renderSunSetupCard?: AnyFunction;
  rollingChannelTotals?: (days?: number) => Record<string, number>;
  rollingDeviceTotals?: (days?: number) => Record<string, number>;
  rollingVitaminDIU?: (days?: number) => number;
  weeklyChannelTier?: (value: number, channel?: string) => number;
  tierLabel?: (tier: number) => string;
  getSessions?: () => any[];
  getActiveSession?: AnyFunction;
  getDevices?: AnyFunction;
  getDeviceSessions?: () => any[];
  cumulativeMEDToday?: AnyFunction;
  cumulativeMEDYesterday?: AnyFunction;
  vitaminDBudgetStatus?: AnyFunction;
  maybeAnalyzeDeviceSessionAfterFinish?: AnyFunction;
  maybeAnalyzeSessionAfterFinish?: AnyFunction;
  _labState?: { currentProfile?: string | null };
  handleDNAFile: (file: File) => Promise<void> | void;
  handleMtDNAFile?: (file: File) => Promise<void> | void;
  importDataJSON: (file: File) => Promise<void> | void;
  isDebugMode?: () => boolean;
  isImportRunning?: () => boolean;
  loadDemoData?: (sex?: string) => Promise<void> | void;
  loadChatHistory?: () => Promise<void> | void;
  loadChatPersonality?: () => void;
  loadChatThreads?: () => void;
  JSZip?: {
    loadAsync(input: ArrayBuffer | Blob): Promise<{
      files: Record<string, {
        dir: boolean;
        name: string;
        async(type: 'blob'): Promise<Blob>;
      }>;
    }>;
  };
  mammoth?: {
    extractRawText(input: { arrayBuffer: ArrayBuffer }): Promise<{ value?: string }>;
  };
  navigate?: (route: string, options?: any) => void;
  nostrGetSelectedNode?: () => string | null;
  nostrSetSelectedNode?: (url: string) => void;
  openClientList?: () => void;
  closeClientList?: () => void;
  openEMFAssessmentEditor?: () => void;
  openSettingsModal?: (tab?: string) => void;
  pdfjsLib?: unknown;
  openProfileShareModal?: (profileId?: string) => void;
  openProfileLocationEditor?: AnyFunction;
  quickLogSunSession?: () => Promise<void> | void;
  quickLogDeviceSession?: AnyFunction;
  openAddDeviceDialog?: AnyFunction;
  openDetailedSessionDialog?: AnyFunction;
  requestPreciseLocation?: AnyFunction;
  pauseSunSession?: (id?: string) => Promise<void> | void;
  resumeSunSession?: (id?: string) => Promise<void> | void;
  flipSidesMidSession?: (id?: string) => Promise<void> | void;
  changeCoverageMidSession?: (id?: string) => Promise<void> | void;
  applySunscreenMidSession?: (id?: string) => Promise<void> | void;
  setOzoneOverrideMidSession?: () => Promise<void> | void;
  _forgotStopPrompt?: (id?: string) => Promise<void> | void;
  _openChannelOnLightPage?: (channel?: string) => void;
  _applyAtmOverrides?: AnyFunction;
  _refreshSunSurfaces?: AnyFunction;
  _resumeActiveTickerIfNeeded?: AnyFunction;
  refreshChartThemeColors?: (options?: { batchSize?: number }) => void;
  refreshSettingsWearables?: () => void;
  rememberModalTrigger?: () => void;
  renderProfileButton?: () => void;
  renderThreadList?: () => void;
  scheduleChartThemeRefresh?: () => void;
  setManualHaplogroup?: (haplogroup: string) => Promise<void> | void;
  showConfirmDialog?: (message: string) => Promise<boolean> | boolean;
  showPromptDialog?: (message: string, options?: any) => Promise<string | null> | string | null;
  showNotification?: (message: string, type?: string, timeoutMs?: number) => void;
  saveImportedData?: AnyFunction;
  loadCatalog?: AnyFunction;
  _cachedCatalog?: { slots?: Record<string, any>; [key: string]: any } | null;
  buildDNAHints?: AnyFunction;
  deleteNote?: AnyFunction;
  detectWearableTrendSlots?: AnyFunction;
  isProductRecsEnabled?: () => boolean;
  loadContextCardTips?: AnyFunction;
  openManualLogForm?: AnyFunction;
  openNoteEditor?: AnyFunction;
  openWearableDetail?: AnyFunction;
  showDetailModal?: AnyFunction;
  startEmptyTour?: AnyFunction;
  startTour?: AnyFunction;
  syncWearableNow?: AnyFunction;
  triggerDNAFilePicker?: AnyFunction;
  loadLightDevicePresets?: AnyFunction;
  renderLightDeviceAffiliateRow?: AnyFunction;
  renderLightTools?: AnyFunction;
  renderActiveDeviceSessionCard?: AnyFunction;
  renderChannelDeficitDeviceRecs?: AnyFunction;
  renderChannelMixVerdict?: AnyFunction;
  renderDevicesSection?: AnyFunction;
  renderEnvironmentAssessmentSummary?: AnyFunction;
  renderOnboardingAIBlock?: AnyFunction;
  renderSunDataSourceSettings?: AnyFunction;
  computeDeficitAxes?: AnyFunction;
  computeIndoorBurden?: AnyFunction;
  computeUVConfidence?: AnyFunction;
  ensureActiveDeviceTicker?: AnyFunction;
  getMeteoConfig?: AnyFunction;
  ingredientDailyTotal?: AnyFunction;
  maybeAnalyzeOnboardingAfterSave?: AnyFunction;
  openLightEnvironmentAssessment?: AnyFunction;
  purgeMeteoCache?: AnyFunction;
  SUN_ENGINE_VERSION?: number;
  AmbientLightSensor?: AmbientLightSensorConstructor;
  _closeAudit?: AnyFunction;
  _closeCCT?: AnyFunction;
  _closeDark?: AnyFunction;
  _closeFlicker?: AnyFunction;
  _closeGlass?: AnyFunction;
  _closeLuxMeter?: AnyFunction;
  _closeSpec?: AnyFunction;
  _dismissAimingGuide?: AnyFunction;
  addRoom?: AnyFunction;
  getRooms?: AnyFunction;
  getSunCoords?: AnyFunction;
  hydrateSession?: AnyFunction;
  logCompletedSession?: AnyFunction;
  maybeAnalyzeMeasurementAfterSave?: AnyFunction;
  getMeasurementsForRoom?: AnyFunction;
  maybeAnalyzeAuditAfterSave?: AnyFunction;
  renderAuditAIBlock?: AnyFunction;
  renderAuditAIDot?: AnyFunction;
  renderBurdenInterp?: AnyFunction;
  renderMeasurementAIInline?: AnyFunction;
  renderRoomAIBlock?: AnyFunction;
  renderScreenAIBlock?: AnyFunction;
  refreshLightEnvironmentAssessment?: AnyFunction;
  saveLightAuditFromUI?: AnyFunction;
  saveMeasurement?: AnyFunction;
  suggestRoomSourceFromSpectrum?: AnyFunction;
  openChatPanel?: AnyFunction;
  openCCTMeter?: AnyFunction;
  openDarknessMeter?: AnyFunction;
  openFlickerDetector?: AnyFunction;
  openLuxMeter?: AnyFunction;
  openSpectrumClassifier?: AnyFunction;
  _fitbitAuth?: unknown;
  _appleHealth?: unknown;
  _ouraAuth?: unknown;
  _polarAuth?: unknown;
  _ultrahumanAuth?: unknown;
  _whoopAuth?: unknown;
  _withingsAuth?: unknown;
  updateChatHeaderTitle?: () => void;
  updateDiscussButton?: () => void;
  updateHeaderDates?: () => void;
  updateHeaderRangeToggle?: () => void;
  updatePersonalityBar?: () => void;
  updateSettingsUI?: () => void;
  updateTweaksUI?: () => void;
}

declare var getMeasurementsForRoom: AnyFunction | undefined;
declare var navigate: AnyFunction | undefined;
declare var openCCTMeter: AnyFunction | undefined;
declare var openDarknessMeter: AnyFunction | undefined;
declare var openFlickerDetector: AnyFunction | undefined;
declare var openLuxMeter: AnyFunction | undefined;
declare var openSpectrumClassifier: AnyFunction | undefined;
declare var renderBurdenInterp: AnyFunction | undefined;
declare var renderMeasurementAIInline: AnyFunction | undefined;
declare var renderRoomAIBlock: AnyFunction | undefined;
declare var renderScreenAIBlock: AnyFunction | undefined;
declare var saveLightAuditFromUI: AnyFunction | undefined;
declare var ingredientDailyTotal: AnyFunction | undefined;
