declare const Buffer: {
  from(value: ArrayBuffer | ArrayLike<number> | string, encoding?: string): {
    toString(encoding?: string): string;
  };
};

type AnyFunction = (...args: any[]) => any;

interface Window {
  _demoLoadingProfileId?: string;
  _snpTableCache?: unknown;
  APP_VERSION?: string;
  applyAccentOverride?: () => void;
  buildSidebar?: () => void;
  callClaudeAPI?: (request: {
    system?: string;
    messages: Array<{ role: string; content: string }>;
    maxTokens?: number;
  }) => Promise<{ text?: string }> | { text?: string };
  cashuDestroyWalletDB?: () => Promise<void> | void;
  cashuGetMintUrl?: () => Promise<string | null> | string | null;
  cashuRestoreWalletFromSeed?: (seed: string) => Promise<void> | void;
  cashuSetMintUrl?: (url: string) => Promise<void> | void;
  Chart?: new (canvas: HTMLCanvasElement, config: unknown) => { destroy(): void };
  closeModal?: () => void;
  closeSettings?: () => void;
  destroyAllCharts?: () => void;
  detectDNAFile?: (header: string) => string | null;
  ensureActiveThread?: () => void;
  exportAllDataJSON?: () => Promise<void> | void;
  exportClientJSON?: (profileId: string, includeChat?: boolean) => Promise<void> | void;
  getInitialView?: () => string;
  getActiveProfileId?: () => string | null;
  getProfileHeight?: (profileId: string) => { height?: number | string | null; unit?: string | null };
  getProfiles?: () => Array<{ id?: string; sex?: string | null }>;
  HAPLOGROUP_LIST?: string[];
  hasAIProvider?: () => boolean;
  fetchAtmosphere?: AnyFunction;
  reconstructSpectrum?: AnyFunction;
  computeChannelDoses?: AnyFunction;
  erythemalSED?: AnyFunction;
  fractionOfMED?: AnyFunction;
  retinalUVdose?: AnyFunction;
  solarZenithAngle?: AnyFunction;
  interpolateAtmosphere?: AnyFunction;
  vitaminDIU?: AnyFunction;
  vitaminDIUPerSession?: AnyFunction;
  pbmJoulesPerCm2?: AnyFunction;
  circadianMelanopicLux?: AnyFunction;
  _skinTypeToFitzpatrick?: AnyFunction;
  geneticVitaminDMultiplier?: AnyFunction;
  renderSessionAIInline?: AnyFunction;
  renderSessionAIDetail?: AnyFunction;
  renderLightChannelsLive?: AnyFunction;
  renderLightTodayStrip?: AnyFunction;
  maybeAnalyzeSessionAfterFinish?: AnyFunction;
  _labState?: { currentProfile?: string | null };
  handleDNAFile: (file: File) => Promise<void> | void;
  handleMtDNAFile?: (file: File) => Promise<void> | void;
  importDataJSON: (file: File) => Promise<void> | void;
  isDebugMode?: () => boolean;
  isImportRunning?: () => boolean;
  loadDemoData?: (sex?: string) => Promise<void> | void;
  loadChatHistory?: () => Promise<void> | void;
  loadChatPersonality?: () => void;
  loadChatThreads?: () => void;
  JSZip?: {
    loadAsync(input: ArrayBuffer | Blob): Promise<{
      files: Record<string, {
        dir: boolean;
        name: string;
        async(type: 'blob'): Promise<Blob>;
      }>;
    }>;
  };
  mammoth?: {
    extractRawText(input: { arrayBuffer: ArrayBuffer }): Promise<{ value?: string }>;
  };
  navigate?: (route: string) => void;
  nostrGetSelectedNode?: () => string | null;
  nostrSetSelectedNode?: (url: string) => void;
  openClientList?: () => void;
  closeClientList?: () => void;
  openEMFAssessmentEditor?: () => void;
  openSettingsModal?: (tab?: string) => void;
  pdfjsLib?: unknown;
  openProfileShareModal?: (profileId?: string) => void;
  quickLogSunSession?: () => Promise<void> | void;
  pauseSunSession?: (id?: string) => Promise<void> | void;
  resumeSunSession?: (id?: string) => Promise<void> | void;
  flipSidesMidSession?: (id?: string) => Promise<void> | void;
  changeCoverageMidSession?: (id?: string) => Promise<void> | void;
  applySunscreenMidSession?: (id?: string) => Promise<void> | void;
  setOzoneOverrideMidSession?: () => Promise<void> | void;
  _forgotStopPrompt?: (id?: string) => Promise<void> | void;
  _openChannelOnLightPage?: (channel?: string) => void;
  refreshChartThemeColors?: (options?: { batchSize?: number }) => void;
  refreshSettingsWearables?: () => void;
  rememberModalTrigger?: () => void;
  renderProfileButton?: () => void;
  renderThreadList?: () => void;
  scheduleChartThemeRefresh?: () => void;
  setManualHaplogroup?: (haplogroup: string) => Promise<void> | void;
  showConfirmDialog?: (message: string) => Promise<boolean> | boolean;
  showNotification?: (message: string, type?: string, timeoutMs?: number) => void;
  _fitbitAuth?: unknown;
  _appleHealth?: unknown;
  _ouraAuth?: unknown;
  _polarAuth?: unknown;
  _ultrahumanAuth?: unknown;
  _whoopAuth?: unknown;
  _withingsAuth?: unknown;
  updateChatHeaderTitle?: () => void;
  updateDiscussButton?: () => void;
  updateHeaderDates?: () => void;
  updateHeaderRangeToggle?: () => void;
  updatePersonalityBar?: () => void;
  updateSettingsUI?: () => void;
  updateTweaksUI?: () => void;
}
