#!/usr/bin/env node
// Compile the isolated Tailwind pilot and retain the existing lazy CSS URL.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = path.join(ROOT, 'css/settings.css');

export async function buildStyles({ outputPath = OUTPUT, check = false }: {
  outputPath?: string; check?: boolean;
} = {}): Promise<void> {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'getbased-styles-'));
  try {
    const compiled = path.join(directory, 'display.css');
    execFileSync(process.execPath, [
      path.join(ROOT, 'node_modules/@tailwindcss/cli/dist/index.mjs'),
      '--input', path.join(ROOT, 'css/settings-display.tailwind.css'),
      '--output', compiled, '--minify',
    ], { cwd: ROOT, stdio: ['ignore', 'ignore', 'pipe'] });
    const [base, utilities] = await Promise.all([
      fs.readFile(path.join(ROOT, 'css/settings.base.css'), 'utf8'),
      fs.readFile(compiled, 'utf8'),
    ]);
    const source = '/* Generated by npm run styles:build; edit settings.base.css or settings-display.tailwind.css. */\n'
      + base.trimEnd() + '\n\n' + utilities.trimEnd() + '\n';
    if (check) {
      const existing = await fs.readFile(outputPath, 'utf8');
      if (existing !== source) throw new Error('Settings CSS is stale; run npm run styles:build');
    } else {
      await fs.writeFile(outputPath, source);
    }
  } finally {
    await fs.rm(directory, { recursive: true, force: true });
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await buildStyles({ check: process.argv.includes('--check') });
}
